Add content char counter, improve invalid form handling
qgis/qgis-feed pull request #59
Opened 2023-12-08 09:37 UTC by Xpirix

- This PR is for the issue #55 

## Changes summary

- Add characters counter in TinyMCE. It counts the total of characters of the field `content` value including HTML tags.
- Stop editing when the max characters are exceeded
- Disallow paste that exceeds max charters
- Disable the buttons `Submit for review` / `Save changes` / `Approve and publish` when the form is not valid (including content field max characters exceeded)
-  Set error styles to red and bigger font size

Please find bellow a GIF demonstrating these changes:

![Form_validation](https://github.com/qgis/qgis-feed/assets/43842786/b7538955-2e29-4de9-a510-1530ba42f48a)

2023-12-08 10:45 UTC, haubourg commented
Looks good to me from your specifications and screen cast 👍

Thanks !

2024-01-03 02:00 UTC, dimasciput commented on qgisfeedproject/qgisfeed/views.py
> +        try:
@Xpirix, could you please create a function for this? That way, you won't need to call it every time. Alos please create a test for the function.

2024-01-03 02:00 UTC, dimasciput requested changes
check my comment

2024-01-03 05:54 UTC, Xpirix commented
@dimasciput , I've made the changes.

2024-01-04 02:48 UTC, dimasciput approved these changes

2024-01-04 02:48 UTC, merged